### ISSUE TITLE
Sorting Todo

### ISSUE THREAD

**Issue by DylanLin29** [DylanLin29/TodoList#12]
- [x] Based on the importance
- [x] Starting order is the created time
- [x] Based on the category
- [x] Based on the status
